update with env

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -29,10 +29,10 @@ jobs:
                         echo "Ruff check did not find issues as it should"
                         exit 1
                     fi
-                    ruff format --check $PROJECT_PATH > /dev/null 2>&1 || EXIT_CODE=$?;
+                    ruff format $PROJECT_PATH > /dev/null 2>&1 || EXIT_CODE=$?;
                     if [ $EXIT_CODE -eq 1 ]; then
                         echo "Ruff format found issues as it should"
                     else
-                        echo "Ruff format did not find issues as it should"
+                        echo "Ruff format did not found issues as it should"
                         exit 1
                     fi
